

TRAIN_DATA_FILE_PATH = '/root/dataset/train512_181201.tfrecords'
VAL_DATA_FILE_PATH = ''

LR = 2.5e-4
BATCH_SIZE = 8
# NUM_SAMPLES = 5000
TRAIN_EPOCHES = 10000
# ======
EPOCH_SIZE = 550
SAVE_CKPT_STEP = 200
VAL_STEP = 10
VAL_EPOCH_SIZE = 100
#====
INPUT_WIDTH = 256
INPUT_HEIGHT = 256
INPUT_CHANNEL = 3

NPOINTS = 16

MODEL_OUTPUT_WIDTH = 256
MODEL_OUTPUT_HEIGHT = 256


HM_SIGMA = 26

TF_IMAGE_WIDTH = 512
TF_IMAGE_HEIGHT = 512
TF_IMAGE_CHANNEL = 3


# FINETUNE_CKPT_PATH = 'result_train/model'

SAVE_ROOT_PATH = 'result_train'



NUM_BBOX = 2

LABEL_DIMS = 2

LOSS_SELF = True
